### PR TITLE
fix(mistral): handle Optional choice.message from v2 SDK

### PR DESCRIPTION
**Pull request by peteski22**
## Description

The mistralai v2 SDK (adopted in #1020) types `choice.message` as `AssistantMessage | None`, but `_create_mistral_completion_from_response` dereferenced `message_data.content` and `message_data.tool_calls` without a None guard. This produced five `union-attr` errors under mypy strict mode:

```
src/any_llm/providers/mistral/utils.py:174: error: Item "None" of "AssistantMessage | None" has no attribute "content"  [union-attr]
src/any_llm/providers/mistral/utils.py:175: error: ... [union-attr]
src/any_llm/providers/mistral/utils.py:181: error: ... [union-attr]
src/any_llm/providers/mistral/utils.py:183: error: ... [union-attr]
src/any_llm/providers/mistral/utils.py:201: error: ... [union-attr]
```

The lint job on `main` has been intermittently failing since #1020 merged — whichever CI run hit the resolver state where mistralai's tightened typing was visible would fail. The most recent failure is on PR #1028.

### Fix

Add an explicit `ValueError` guard at the top of the loop so the converter fails loudly rather than silently emitting a truncated `ChatCompletion`. A real chat-completion choice always carries a message; if the SDK ever hands us `None`, we want to know rather than drop the choice silently.

Includes a unit test that covers the new guard path.

## PR Type

- 🐛 Bug Fix

## Relevant issues

Regression introduced by #1020 (`fix(mistral): update imports for mistralai v2 SDK`).

## Checklist

- [x] I understand the code I am submitting.
- [x] I have added unit tests that prove my fix/feature works
- [x] I have run this code locally and verified it fixes the issue.
- [x] New and existing tests pass locally
- [x] Documentation was updated where necessary
- [x] I have read and followed the [contribution guidelines](https://github.com/mozilla-ai/any-llm/blob/main/CONTRIBUTING.md)
- [x] **AI Usage:**
    - [x] AI was used for drafting/refactoring.

## AI Usage Information

- AI Model used: Claude Opus 4.6 (1M context)
- AI Developer Tool used: Claude Code
- Any other info you'd like to share:

- [ ] I am an AI Agent filling out this form (check box if true)

### CODE REVIEW

**Review by njbrake — APPROVED** [review]
Looks good to me! 🚀
